name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Create and copy out folder to GitHub source branch
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: source
          FOLDER: out

      - name: Copy server folder to GitHub source branch
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: source
          FOLDER: server
          CLEAN: false

      - name: Deploy Github source branch to Digital Ocean
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
     
          script: |
            cd /var/www/html/group3 
            rm -rf ./* 
            git clone https://github.com/schultzp2020/Agile-Group-3.git
            cd ./Agile-Group-3 
            git checkout source 
            cd .. 
            mv ./Agile-Group-3/* . 
            rm -rf ./Agile-Group-3 